Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_SETTINGS = void 0;
exports.DEFAULT_SETTINGS = {
    defaultUnit: "seconds",
    format: "compact",
    minValue: 1,
    maxValue: 31557600000,
    showBreakdown: true,
    showUnitLabel: true,
    contextClues: true,
    ignorePatterns: [
        "^0x[0-9a-f]+$",
        "^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$",
        "^\\d{4}-\\d{2}-\\d{2}$",
        "^\\d{10,}$",
    ],
    keywords: [
        "timeout",
        "interval",
        "delay",
        "duration",
        "ttl",
        "expiry",
        "expire",
        "retention",
        "age",
        "period",
        "rate",
        "throttle",
        "backoff",
        "retry",
        "wait",
        "sleep",
        "pause",
        "hold",
        "cache",
        "session",
    ],
};
//# sourceMappingURL=index.js.map
